server:
  port: 9002
spring:
  application:
    name: favourites-service
  zipkin:
    enabled: true
    base-url: http://${ZIPKIN_SERVER_IP:localhost}:9411  
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/nutritionist?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:guru@123}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka

# Hide startup logs
logging:
  level:
    org:
      springframework:
        cache: TRACE