server:
  port: 8001
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/nutritionist-user}
    
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
      
# Hide startup logs
logging:
  level:
    org:
      springframework:
        cache: TRACE
        


jwt:
  secret: secretkey
